### ISSUE TITLE
Input files explanation required

### ISSUE THREAD

**Issue by raveancic** [xinghuq/KLFDAPC#4]
Thanks for this tool. Unfortunately I did not find a clear explanation on which format the tool accept as input/how to create the .gds. I think this can be really useful for reproducibility with other data set.

**Comment by xinghuq** [comment]
Hi, thanks for your feedback, I just updated the explanation in readme file:

GDS is portable across platforms with hierarchical structure to store
multiple scalable array-oriented data sets with metadata information.
Details can be found [here](
http://bioconductor.org/packages/release/bioc/vignettes/gdsfmt/inst/doc/gdsfmt.html
).

You can convert PLINK/Oxford files to GDS using SNPRelate (Zheng et al.
2012).

[snpgdsBED2GDS Conversion from PLINK BED to GDS](
https://rdrr.io/bioc/SNPRelate/man/snpgdsBED2GDS.html).
[snpgdsGEN2GDS Conversion from Oxford GEN format to GDS](
https://rdrr.io/bioc/SNPRelate/man/snpgdsGEN2GDS.html).
[snpgdsPED2GDS Conversion from PLINK PED to GDS](
https://rdrr.io/bioc/SNPRelate/man/snpgdsPED2GDS.html)

Below, is an example on how to convert PLINK bed files to GDS,

``````
library("SNPRelate")
# PLINK BED files
bed.fn ="/file_location/target.bed"
fam.fn = "/file_location/target.fam"
bim.fn = "/file_location/target.bim"

# convert
snpgdsBED2GDS(bed.fn, fam.fn, bim.fn, "HapMap.gds")

# open
genofile <- snpgdsOpen("HapMap.gds")
genofile

# close
snpgdsClose(genofile)
``````

**Comment by raveancic** [comment]
Super, thanks!

**Comment by raveancic** [comment]
Super Thanks!
