### ISSUE TITLE
Error in matrix(1, N, M) : non-numeric matrix extent when running klfdapc

### ISSUE THREAD

**Issue by MarcGose** [xinghuq/KLFDAPC#5]
Hello,

I wanted to try out klfdapc on my SNP dataset, following the tutorial on this Github.
Everything seems to work fine until the kfldapc step, where I get the error "Error in matrix(1, N, M) : non-numeric matrix extent"

I tried assigning random labels as in the SARS-Cov-2 tutorial and this worked, so I reckon it must be something with my population codes, but I can't seem to figure out what it is. I would greatly appreciate any help with this.

This is my code:

popsex <- read.table("pop_file.info")
pop_file <- popsex$V1

samp.annot <- data.frame(pop_file)

snpgdsVCF2GDS(vcf.fn = "C:/Users/MarcG/OneDrive/Desktop/VCF/WSD_GLs.vcf", out.fn = "WSD_GLs_GDS")

(genofile <- snpgdsOpen("WSD_GLs_GDS", readonly = FALSE))

read.gdsn(index.gdsn(genofile, "sample.id"))
read.gdsn(index.gdsn(genofile, "snp.rs.id"))
read.gdsn(index.gdsn(genofile, "genotype"))
add.gdsn(genofile, "sample.annot", samp.annot)
pop_code <- read.gdsn(index.gdsn(genofile, "sample.annot"))
pop_code <- read.gdsn(index.gdsn(genofile, path="sample.annot/pop_file"))
pop_code=factor(pop_code,levels=unique(pop_code))

pcadata <- SNPRelate::snpgdsPCA(genofile, autosome.only = FALSE)

snpgdsClose(genofile)

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

pcanorm=apply(pcadata$eigenvect[,1:20], 2, normalize)

kmat <- kmatrixGauss(pcanorm,sigma=5)

klfdapc=KLFDA(kmat, pop_code, r=3, knn = 2)
Error in matrix(1, N, M) : non-numeric matrix extent

**Comment by xinghuq** [comment]
Hi, most likely your "pop_code" in the "pop_code <- read.gdsn(index.gdsn(genofile, "sample.annot"))"
”pop_code <- read.gdsn(index.gdsn(genofile, path="sample.annot/pop_file"))“ are not uniquely pop factors.
Please check these pop_code first, and see what are they.
Please use your own real pop labels instead from "”pop_code <- read.gdsn(index.gdsn(genofile, path="sample.annot/pop_file"))“", make sure that knn < the minimum number of individuals in a pop.

Cheers,

Xinghu

**Comment by MarcGose** [comment]
Thanks Xinghu, that was it!

Just aother short question:
Given that requirement for the knn parameter, is there any way to incorporate a population that is respresented by only one individual?

**Comment by xinghuq** [comment]
The answer is yes. One of the advantages of KLFDAPC is that it can preserve multimodal structures within pops, you can label a single individual to a higher level metapop. For example, if you think it can be merged into a very close pop that is different from other pops when running klfdapc, this can avoid removing single individual, after you get klfdapc features you can then plot it using true individual labels. This is one of the highlights of this method.

Cheers,

Xinghu

**Comment by MarcGose** [comment]
Thank you so much for your help Xinghu!
Excited to play more with this method soon.

Cheers,

Marc

**Comment by xinghuq** [comment]
The answer is yes. One of the advantages of KLFDAPC is that it can preserve
multmodal structures within pops, you can label a single individual to a
higher level metepop. For example, if you think it can be merged into a
very close pop that is different from other pops when running klfdapc, this
can avoid removing single individual, after you get klfdapc features you
can then plot it using true individual labels. This is one of the
highlights of this method.

Cheers,

Xinghu
